version: '3.8'

services:
  main-bot:
    build:
      context: .
      target: main-bot
    container_name: main-bot
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./price.txt:/app/price.txt
    restart: unless-stopped
    depends_on:
      - mysql

  admin-bot:
    build:
      context: .
      target: admin-bot
    container_name: admin-bot
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    depends_on:
      - mysql

  scheduler:
    build:
      context: .
      target: scheduler
    container_name: scheduler
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
